require('sinatra')
require('sinatra/reloader')
require('./lib/author')
require('pry')
require('./lib/book')
require('./lib/patron')
# require('rb-readline')
also_reload('lib/**/*.rb')
require('pg')
require('./db_access.rb')